### ISSUE TITLE
please note occasional divergence of pysmiles' hcount vs. RDKit

### ISSUE THREAD

**Issue by nbehrnd** [pckroon/pysmiles#19]
Dear developers of pysmiles,

please note a recent post on [mattermodelling.se](https://mattermodeling.stackexchange.com/questions/6460/rdkit-and-pysmiles-results-differ-on-some-smiles-strings) which eventually compares the hydrogen count per non-H atom by pysmiles and RDKit for an *N*-alkylated dihydrobenzimidazole.  Apparently, the present version 1.0.1 of pysmiles errs about this example, and wrongly assigns (still) a hydrogen present *as if* neuter nitrogen were tetravalent.

Since the two answers to the OP share MWEs and detailed results, it is possible to equally check the parent non-alkylated structure (`c12ccccc1NCN2`); in this case, the error is not observed.

**Comment by pckroon** [comment]
Thanks for the report (and sorry for the slow reply, I was stuck without internet due to a move).
I'll need a bit more time to dig in to the details here, although the main culprit is the detection/analysis of aromatic regions.

**Comment by nbehrnd** [comment]
I'm not aware if the systematic comparison of the output (re hybridization) offered by pysmiles vs. the by other programs like RDKit may become/already is part of checking the consistency, or not beyond the ones based on pytest.

Thus, rather out of curiosity, a doodle using OpenBabel was set up.  Two differences to your program are identified; namely systematic difference of the labels about the atom types from those used by you and RDKit, and perhaps more importantly, the count of the atom indices starts by one.

Feel free to use the conceptual script as you like.  The archive contains both an earlier doodle in a Jupyter notebook, as well as a script just for the CLI.

[check_openbabel.zip](https://github.com/pckroon/pysmiles/files/7033157/check_openbabel.zip)

**Comment by pckroon** [comment]
Many thanks for the help!

For the smiles `"c1ccncc1CNO"` openbabel and pysmiles produce the same result as far as I can see:
```
0 {'element': 'C', 'charge': 0, 'aromatic': True, 'hcount': 1}
1 {'element': 'C', 'charge': 0, 'aromatic': True, 'hcount': 1}
2 {'element': 'C', 'charge': 0, 'aromatic': True, 'hcount': 1}
3 {'element': 'N', 'charge': 0, 'aromatic': True, 'hcount': 0}
4 {'element': 'C', 'charge': 0, 'aromatic': True, 'hcount': 1}
5 {'element': 'C', 'charge': 0, 'aromatic': True, 'hcount': 0}
6 {'element': 'C', 'charge': 0, 'aromatic': False, 'hcount': 2}
7 {'element': 'N', 'charge': 0, 'aromatic': False, 'hcount': 1}
8 {'element': 'O', 'charge': 0, 'aromatic': False, 'hcount': 1}

  1 Car 2
  2 Car 2
  3 Car 2
  4 Nar 2
  5 Car 2
  6 Car 2
  7 C3  3
  8 Nox 3
  9 O3  3
```

For "OCCn2c(=N)n(CCOc1ccc(Cl)cc1Cl)c3ccccc23" they indeed produce different results for the bicyclic/extracyclic aromatic moiety (as expected).
I would appreciate some help to come up with a (good/simple) algorithm to decide whether an atom is (anti)aromatic. The current implementation is (obviously) too simplistic.
Once that's implemented it should /absolutely/ be added to the testsuite.

 > perhaps more importantly, the count of the atom indices starts by one.
I don't think this is an issue. I adhere to python standards where we start counting at 0. Besides, the numbering is fully arbitrary. Pysmiles will number the atoms in the order in which they're in the smiles, but this is not something other software has to do. If you want to be sure/align the produced graphs/molecules you need to solve the graph isomorphism. But that's out of scope here and for pysmiles (besides, networkx has good solutions for it).

**Comment by nbehrnd** [comment]
> I would appreciate some help to come up with a (good/simple) algorithm to decide whether an atom is (anti)aromatic. The current implementation is (obviously) too simplistic.
> Once that's implemented it should /absolutely/ be added to the testsuite.

Without background in graph theory I'm not sure if these the two
publications just seen may present an entry to identify easier/more
reliably aromatic/antiaromatic cycles, than pysmiles currently does.
Nor if the content of these publications partly sum up knowledge
already implemented in pysmiles and how efficient the implementation
of their concepts presented are:

[1]
https://depth-first.com/articles/2020/02/10/a-comprehensive-treatment-of-aromaticity-in-the-smiles-language/

[2]
https://depth-first.com/articles/2021/06/30/writing-aromatic-smiles/

One of the programs the two mention again is RDKit which assigned the
structure problematic to pysmiles correctly.  Since RDKit's  source
code is public and under the permissive umbrella of a BSD license,
maybe Noël O'Boyle and Greg Landrum (as two prominent developers
there) provide permission to re-use logic/algorithms or/and snippets
of implementation of RDKit's working code in pysmiles provided there
is proper credit, attribution, and acknowledgment of the work.

Reading this, an other name which comes to my mind would be Geoff
Hutchison (for leading the development of OpenBabel and Avogadro, the
later a GUI equally dealing with the correct visualization e.g., of
aromatic cycles).

**Comment by pckroon** [comment]
Thanks for the links. It's interesting to note that in 2021 aromaticity in SMILES is still ill-defined :)

I need a bit more time to really digest this, and decide on what the desired behaviour is as well. 
Looking at the molecule in your opening post the assignment of implicit hydrogens is actually very suspicious independent of aromaticity.

As for parser behaviour, I see three options.

1) Take the provided SMILES as ground truth. If that says something is aromatic, it is. This would also leave kekulized input as-is.
2) Re-assess aromaticity so that kekulized cycles may become aromatic. 
3) Re-assess all aromaticity. This means atoms that are aromatic in the input may be made non-aromatic.

Anything that's not option 1 is hard :'). Then again, some method of detecting aromaticity is desirable for the writer. 

To be continued...
