### ISSUE TITLE
`reinterpret_aromatic` erases aromatic rings containing a `N+`

### ISSUE THREAD

**Issue by Kroppeb** [pckroon/pysmiles#35]
Example: `OCCc1c(C)[n+](cs1)Cc2cnc(C)nc2N` or `CCc(c1)ccc2[n+]1ccc3c2[nH]c4c3cccc4`

**Comment by pckroon** [comment]
What do you mean by "erases aromatic rings"? Does it remove atoms or flag them as not aromatic?

**Comment by Kroppeb** [comment]
It removes the flag.
