### ISSUE TITLE
Treasure Hunt

### ISSUE THREAD

**Issue by fgrunewald** [pckroon/pysmiles#43]
Smiles that are aromatic and worked before the latest aromatic update:

```
dideoxyaraan1oxide2fluoro C1C(F)C(n2c3ncn(=O)c(N)c3nc2)OC1CO
2,5-dime-3,6-dichloropyrazine-1-oxide Cc1nc(Cl)c(C)n(=O)c1Cl
2,5-dime-6-chloropyrazine-1-oxide Cc1n(=O)c(Cl)c(C)nc1
2,3-di(4-cl-ph)-5-cl-pyrazine-1-oxide c1c(c3nc(Cl)cn(=O)c3c2ccc(Cl)cc2)ccc(Cl)c1
5-(1-oxo-1lambda~5~-pyridin-3-yl)pyrrolidin-2-one O=C1CCC(N1)c2cccn(=O)c2
```

**Comment by pckroon** [comment]
1) `C1C(F)C(n2c3ncn(=O)c(N)c3nc2)OC1CO`
  n8 is uncharged and has 4 bonds even without being aromatic. So it gets pruned, and *should* break.
2) `Cc1nc(Cl)c(C)n(=O)c1Cl`
  Same for n7.
3) `Cc1n(=O)c(Cl)c(C)nc1`
  n2
4) `c1c(c3nc(Cl)cn(=O)c3c2ccc(Cl)cc2)ccc(Cl)c1`
  n7
5) `O=C1CCC(N1)c2cccn(=O)c2`
  n10
