### ISSUE TITLE
Add pysmiles to conda-forge

### ISSUE THREAD

**Issue by TimoSommer** [pckroon/pysmiles#46]
Hey, are there any plans to add pysmiles to conda-forge? I am using pysmiles in a python package I am soon gonna push to conda-forge myself, but it seems to be impossible to use a pip package as requirement for a conda package, understandably.

I have also seen that apparently it's quite simple to publish to conda if you're already on the pypi index as pysmiles is. There are functionalities like conda skeleton or grayskull that seem to make this quite simple. If it is out of your current availibilites to have a look at that, I could also try to find some time to have a look into this. I'm also doing all of this for the first time though.

**Comment by pckroon** [comment]
Hello hello!
I don't (usually) use conda myself, so I don't really have the intention to add and maintain pysmiles on conda-forge. If you're willing to maintain it I have no problems with you creating the conda-forge feedstock. If that requires changes from pysmiles feel free to open a pull request.

**Comment by TimoSommer** [comment]
Thanks for your quick answer! For now, I have managed to install my package purely via pip as well so I don't need pysmiles to be on conda anymore either. Please feel free to close this issue.

**Comment by pckroon** [comment]
I'm happy you found a solution/workaround :)
Would you mind posting it here for posterity? You can then close the issue yourself.

**Comment by TimoSommer** [comment]
Sure thing, although unfortunately my workaround has nothing to do with pysmiles. I just found out that it's possible to install  openbabel via the openbabel-wheels pip package, which I wasn't aware of before and which is required by my package :)
