### ISSUE TITLE
Stereochemistry

### ISSUE THREAD

**Issue by nshervt** [pckroon/pysmiles#9]
I was trying to get the nodes and adjacency matrix of a drug-like molecule. While doing this, I encountered the following message:

`I don't quite know how to handle stereo yet...`

However, code returns nodes vector and adjacency matrix that I wanted. I was wondering if the returned values are valid or they should be discarded.

**Comment by pckroon** [comment]
Hi,

Yes, the graph parsed should still be valid, but any stereochemical information (R/S and E/Z) will have been discarded.

**Comment by nshervt** [comment]
Thanks!
